---
language: python
python:
- '2.7'
install:
- 'pip install yamllint==1.15.0'
- 'pip install cfn-lint==0.14.0'
script:
- 'find examples -type f -name ''example.yml'' | while read file; do set -ex && yamllint "$file"; done;'
- 'find examples -type f -name ''example.yml'' | while read file; do set -ex && cfn-lint -t "$file"; done;'
- 'find examples -type f -name ''example.yml'' -not -name .eslintrc.yml | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;'
