---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'cfn-modules: Serverless SQS queue example'
Resources:
  Queue:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: './node_modules/@cfn-modules/sqs-queue/module.yml'
  QueueEventSource:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        LambdaModule: !GetAtt 'Function.Outputs.StackName'
        QueueModule: !GetAtt 'Queue.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/lambda-event-source-sqs-queue/module.yml'
  Function:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Handler: 'example.handler'
        Runtime: 'nodejs8.10'
        ReservedConcurrentExecutions: 5
      TemplateURL: './node_modules/@cfn-modules/lambda-function/module.yml'
Outputs:
  QueueName:
    Value: !GetAtt 'Queue.Outputs.Name'
